// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYW00JukPRZALtiaeEhU-tfnwUv6dpWjc',
    appId: '1:273895802413:web:8cdfe7698d9fc864101aa4',
    messagingSenderId: '273895802413',
    projectId: 'crm-mobile-applications',
    authDomain: 'crm-mobile-applications.firebaseapp.com',
    storageBucket: 'crm-mobile-applications.firebasestorage.app',
    measurementId: 'G-WFSK28JBXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtD7Oq8sfLERJ83gockuzBa159pI8Sk2U',
    appId: '1:273895802413:android:0c0c336b749c7802101aa4',
    messagingSenderId: '273895802413',
    projectId: 'crm-mobile-applications',
    storageBucket: 'crm-mobile-applications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXa7LmUKWYe2kPm7_Bv_wHYbh-X6AO9-0',
    appId: '1:273895802413:ios:23ddbbc8ae56fca8101aa4',
    messagingSenderId: '273895802413',
    projectId: 'crm-mobile-applications',
    storageBucket: 'crm-mobile-applications.firebasestorage.app',
    iosBundleId: 'com.example.crmApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXa7LmUKWYe2kPm7_Bv_wHYbh-X6AO9-0',
    appId: '1:273895802413:ios:23ddbbc8ae56fca8101aa4',
    messagingSenderId: '273895802413',
    projectId: 'crm-mobile-applications',
    storageBucket: 'crm-mobile-applications.firebasestorage.app',
    iosBundleId: 'com.example.crmApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYW00JukPRZALtiaeEhU-tfnwUv6dpWjc',
    appId: '1:273895802413:web:c0938043e8af50ee101aa4',
    messagingSenderId: '273895802413',
    projectId: 'crm-mobile-applications',
    authDomain: 'crm-mobile-applications.firebaseapp.com',
    storageBucket: 'crm-mobile-applications.firebasestorage.app',
    measurementId: 'G-ELSL6JPKJX',
  );
}
